pipeline:
  name: Build java-hello-world-with-maven
  identifier: Build_mahesh4346_java_hello_world_with_maven_1712262583617
  projectIdentifier: Maven_Java_Project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
              - step:
                  type: Run
                  name: Maven Build
                  identifier: Maven_Build
                  spec:
                    shell: Sh
                    command: mvn clean package dependency:copy-dependencies
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        description: ""
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1712256360319
        repoName: mahesh4346/java-hello-world-with-maven
        build: <+input>
